In [ ]:
# Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import plotly.express as px
import csv

<>:11: SyntaxWarning: invalid escape sequence '\P'
<>:11: SyntaxWarning: invalid escape sequence '\P'
C:\Users\razor\AppData\Local\Temp\ipykernel_24780\1012531469.py:11: SyntaxWarning: invalid escape sequence '\P'
  df = pd.read_csv('C:\Projects\loan.csv')
C:\Users\razor\AppData\Local\Temp\ipykernel_24780\1012531469.py:11: DtypeWarning: Columns (19,47,55,112,123,124,125,128,129,130,133,139,140,141) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('C:\Projects\loan.csv')

In [ ]:
df = pd.read_csv('C:\Projects\loan.csv')
df.head(5)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,30000,30000,30000.0,60 months,18.94,777.23,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,4000,4000,4000.0,36 months,18.94,146.51,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30000,30000,30000.0,60 months,16.14,731.78,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
columns_to_keep = ['loan_amnt', 'int_rate', 'installment', 'grade', 'emp_length', 'home_ownership', 'annual_inc', 'loan_status', 'purpose']
loan_df = df[columns_to_keep]
loan_df

loan_df['loan_percent_income'] = loan_df['loan_amnt'] / loan_df['annual_inc']
loan_df

C:\Users\razor\AppData\Local\Temp\ipykernel_24780\3380914197.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  loan_df['loan_percent_income'] = loan_df['loan_amnt'] / loan_df['annual_inc']

,loan_amnt,int_rate,installment,grade,emp_length,home_ownership,annual_inc,loan_status,purpose,loan_percent_income
0,2500,13.56,84.92,C,10+ years,RENT,55000.0,Current,debt_consolidation,0.045455
1,30000,18.94,777.23,D,10+ years,MORTGAGE,90000.0,Current,debt_consolidation,0.333333
2,5000,17.97,180.69,D,6 years,MORTGAGE,59280.0,Current,debt_consolidation,0.084345
3,4000,18.94,146.51,D,10+ years,MORTGAGE,92000.0,Current,debt_consolidation,0.043478
4,30000,16.14,731.78,C,10+ years,MORTGAGE,57250.0,Current,debt_consolidation,0.524017
...,...,...,...,...,...,...,...,...,...,...
2260663,12000,14.08,279.72,C,10+ years,MORTGAGE,58000.0,Current,debt_consolidation,0.206897
2260664,12000,25.82,358.01,E,< 1 year,MORTGAGE,30000.0,Fully Paid,debt_consolidation,0.400000
2260665,10000,11.99,332.10,B,10+ years,OWN,64000.0,Current,debt_consolidation,0.156250
2260666,12000,21.45,327.69,D,NaN,RENT,60000.0,Current,debt_consolidation,0.200000
2260667,16550,21.45,451.94,D,3 years,RENT,60000.0,Current,credit_card,0.275833